version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colab_static_reviewer
    ports:
      - "3000:80"
    volumes:
      - ./uploaded_files:/app/uploaded_files
      - ./screenshots:/app/screenshots
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  postgres:
    image: postgres
    container_name: colab_static_reviewer_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=colab_static_reviewer
